Add Flux to the integrations list
ossf/ossf-landscape pull request #200
Opened 2022-11-05 10:16 UTC by developer-guy

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Co-authored-by: Stefan Prodan <stefan.prodan@gmail.com>

/cc @stefanprodan

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~10 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

2022-11-05 10:22 UTC, developer-guy commented
Hello @tracymiranda, as the error says[^1], it seem I could not add Flux for both the "signed-with" and "integrations" sections:

```shell
1:18:15 PM: FATAL: Duplicate item: Cloud Native Computing Foundation (CNCF) Flux at path Sigstore / Integrations
1:18:15 PM: FATAL: Duplicate item: Cloud Native Computing Foundation (CNCF) Flux at path Sigstore / Signed With
```

[^1]: https://app.netlify.com/sites/ossflandscape/deploys/636638136eb8400008f72bb1#L180

2022-11-05 12:29 UTC, tracymiranda commented
It won't allow duplicate names so have to change name to something like Flux (Integration).

2022-11-05 17:55 UTC, stefanprodan requested changes
Please let’s use a link to the official docs which are kept up to date.

2022-11-05 17:55 UTC, stefanprodan commented on landscape.yml
> +              how_to_verify_url: https://fluxcd.io/blog/2022/10/prove-the-authenticity-of-oci-artifacts/
```suggestion
              how_to_verify_url: https://fluxcd.io/flux/cheatsheets/oci-artifacts/#signing-and-verification
```

2022-11-06 09:06 UTC, developer-guy commented
Hi @tracymiranda, it seems that it is not only related to duplicating the names, but it also does not allow any duplication of the fields in the given spec🤔

2022-11-07 17:08 UTC, tracymiranda commented
I think there is also an issue because that section is full (and it won't automatically resize stuff). Let me look at making some layout modifications first then we can address how to resolve this...

2022-11-08 15:27 UTC, tracymiranda commented
OK I've made more space with #202 

@developer-guy looking at the kyverno entry, it is only the github url that cannot be duplicated, so either find a different url to link to or leave it out in one of the entries.

2022-11-09 16:50 UTC, tracymiranda commented
Looks like it is complaining about the space issue, you may need to merge in my changes from #202

2022-11-09 16:56 UTC, stefanprodan commented
Please let's swap labels, remove `Integration` from here and add `Signed With` to the other one, to match Kyverno. Anyway feels very strange to have this note in the project name.

2022-11-09 17:11 UTC, stefanprodan requested changes
The flux repo URL is wrong

2022-11-09 17:11 UTC, stefanprodan commented on landscape.yml
> +            repo_url: https://github.com/fluxcd/flux
```suggestion
            repo_url: https://github.com/fluxcd/flux2
```

2022-11-09 17:17 UTC, stefanprodan approved these changes
LGTM

Thanks @developer-guy and @tracymiranda 🏅

2022-11-09 17:20 UTC, tracymiranda commented
Awesome thank you!

2022-11-09 17:20 UTC, merged